name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11 # Não tenho certeza do porque  3.11, mas é o que tinha no tutorial
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 3. Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 5. Run tests with pytest
        run: pytest --junitxml=pytest-report.xml || true
        env:
          PYTHONPATH: .

      - name: 6. Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: pytest-report.xml
          reporter: jest-junit
          fail-on-error: "true"

      - name: 7. Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint
