name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.11 # Não tenho certeza do porque  3.11, mas é o que tinha no tutorial
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 3. Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 4. Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 5. Run tests with pytest
        run: pytest --junitxml=pytest-report.xml || true
        env:
          PYTHONPATH: .

      - name: 6. Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Pytest Results
          path: pytest-report.xml
          reporter: jest-junit
          fail-on-error: "true"

      - name: 7. Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v4

      - name: 2. Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 3. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  discord:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs:
      - test-and-lint
      - docker
    if: always()
    steps:
      - name: Testar se secret existe (sem printar valor!)
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "Webhook não encontrado!"
            exit 1
          else
            echo "Webhook encontrado!"
          fi
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: >
            CI Pipeline status: ${{ job.status }}  
            Commit: ${{ github.sha }}  
            Branch: ${{ github.ref_name }}  
            By: ${{ github.actor }}
